inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 3.2.2
  TargetRailsVersion: 7.0.7
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/migrate/**/*'
    - 'db/schema.rb'
    - 'vendor/**/*'

require:
  - rubocop-performance
  - rubocop-rails
