AllCops:
  TargetRubyVersion: 3.2.2
  TargetRailsVersion: 7.0.7
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/migrate/**/*'
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'Gemfile'
    - 'tmp/**/*'
    - 'config/environments/*'
    - 'config/puma.rb'
    - 'config/importmap.rb'
    - 'config/boot.rb'
    - 'config/application.rb'
    - 'config/initializers/assets.rb'
    - 'config/initializers/filter_parameter_logging.rb'
    - 'config/initializers/devise.rb'
    - 'config/environment.rb'
    - 'config.ru'
    - 'test/**/*'
    - 'Rakefile'

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-capybara

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'app/helpers/application_helper.rb'
