// Configure your import map in config/importmap.rb. Read more: https://github.com/rails/importmap-rails
import "@hotwired/turbo-rails"
import "controllers"
import "custom/rating"
import "chartkick"
import "Chart.bundle"
import "custom/modal"
import "custom/autocomplete_search"
import "custom/scroll_indicator"
import "custom/loading"
import "custom/image_modal"
